version: "3"

services:
  main:
    image: httpd:${HTTPD_IMG_VERSION}
    networks:
      - default
      - lewatch
    ports:
      - "${FACADE_INTERFACE}:${HTTP_PORT}:80"
    extra_hosts:
      - "${FACADE_DOMAIN}:${FACADE_INTERFACE}"
    volumes:
      - ./volumes/html:/usr/local/apache2/htdocs/
    environment:
      - TZ=CST-8
      - VIRTUAL_HOST=${SERVER_DOMAIN}
      - LETSENCRYPT_HOST=${SERVER_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_CONTACT_EMAIL}
    restart: unless-stopped

networks:
  lewatch:
    external:
      name: hostproxy_default
